# Generated by Django 2.1.1 on 2018-09-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0006_auto_20180927_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fist_name',
            field=models.CharField(default='', max_length=42),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=42),
        ),
    ]
