# Generated by Django 2.1.1 on 2018-09-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0009_auto_20180927_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/profile.png', upload_to='images/'),
        ),
    ]
