# Generated by Django 2.1.1 on 2018-09-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0011_auto_20180928_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='grumblr/static/images/profile.png', upload_to='grumblr/static/images/'),
        ),
    ]
