# Generated by Django 2.1.1 on 2018-09-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0014_auto_20180928_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/profile.png', upload_to='images/%Y/%m/%d/'),
        ),
    ]
