# Generated by Django 2.1.1 on 2018-09-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0015_auto_20180928_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(to='grumblr.Profile'),
        ),
    ]
