# Generated by Django 2.1.1 on 2018-09-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0018_auto_20180928_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/profile.png', upload_to='images/%Y/%m/%d/'),
        ),
    ]
