# Generated by Django 2.1.1 on 2018-10-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0020_auto_20181015_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
